development:
  store_id: <%= ENV.fetch('FGA_STORE_ID', nil) %>
  model_id: <%= ENV.fetch('FGA_MODEL_ID', nil) %>
  api_url: <%= ENV.fetch('FGA_API_URL', nil) || 'http://localhost:8080' %>
  client_id: <%= ENV.fetch('FGA_CLIENT_ID', nil) %>
  client_secret: <%= ENV.fetch('FGA_CLIENT_SECRET', nil) %>
  issuer: <%= ENV.fetch('FGA_TOKEN_ISSUER', nil) %>
  audience: <%= ENV.fetch('FGA_TOKEN_AUDIENCE', nil) %>
